### ISSUE TITLE
VM Creation/Deletion blocks the reconciler thread until completion

### ISSUE THREAD

**Issue by awesomenix** [openshift/cluster-api-provider-azure#30]
/kind bug

**What steps did you take and what happened:**
Right now we block on creation/update and deletion of VMs instead it would be better to requeue and unblock the reconciler thread for other operations

**What did you expect to happen:**

we handle the case here

https://github.com/openshift/cluster-api-provider-azure/blob/4986149e7292b524826605c4dd91e87fcfd4ae9f/pkg/cloud/azure/actuators/machine/reconciler.go#L535

where if its not succeeded it automatically requeues after a minute https://github.com/openshift/cluster-api-provider-azure/blob/4986149e7292b524826605c4dd91e87fcfd4ae9f/pkg/cloud/azure/actuators/machine/actuator.go#L81

technically this means all we need to do is to remove this waitforcompletion here

https://github.com/openshift/cluster-api-provider-azure/blob/4986149e7292b524826605c4dd91e87fcfd4ae9f/pkg/cloud/azure/services/virtualmachines/virtualmachines.go#L194

Same goes for delete as well

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: latest
- Kubernetes version: (use `kubectl version`): latest
- OS (e.g. from `/etc/os-release`):

**Comment by ingvagabund** [comment]
Implemented through https://github.com/openshift/cluster-api-provider-azure/pull/37
